name: Scheduled Test Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print timestamp
        run: |
          echo "Workflow läuft:"
          date

      - name: Simple test
        run: |
          echo "Hello from scheduled GitHub Action"
          echo "Everything is OK"
