name: Render Rmd daily

on:
  schedule:
    - cron: "10 14 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest

    env:
      SOSCI_API_KEY: ${{ secrets.SOSCI_API_KEY }}
      SOSCI_PROJECT_ID: ${{ secrets.SOSCI_PROJECT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install renv
        run: R -e "install.packages('renv')"

      - name: Restore packages
        run: R -e "renv::restore()"

      - name: Render Rmd
        run: R -e "rmarkdown::render('index.Rmd', output_file='index.html')"

      - name: Commit HTML
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions@github.com'
          git add index.html
          git commit -m 'update html' || echo 'no changes'
          git push
